			/* libtiff/tif_config.h.  Generated by configure.  */
			/* libtiff/tif_config.h.in.  Generated from configure.ac by autoheader.  */

			/* Support CCITT Group 3 & 4 algorithms */
			#cmakedefine CCITT_SUPPORT 1

			/* Pick up YCbCr subsampling info from the JPEG data stream to support files
			   lacking the tag (default enabled). */
			#cmakedefine CHECK_JPEG_YCBCR_SUBSAMPLING 1

			/* Support C++ stream API (requires C++ compiler) */
			#cmakedefine CXX_SUPPORT 1

			/* Treat extra sample as alpha (default enabled). The RGBA interface will
			   treat a fourth sample with no EXTRASAMPLE_ value as being ASSOCALPHA. Many
			   packages produce RGBA files but don't mark the alpha properly. */
			#cmakedefine DEFAULT_EXTRASAMPLE_AS_ALPHA 1

			/* Use the Apple OpenGL framework. */
			#cmakedefine HAVE_APPLE_OPENGL_FRAMEWORK 1

			/* Define to 1 if you have the <assert.h> header file. */
			#cmakedefine HAVE_ASSERT_H 1

			/* Define to 1 if you have the <dlfcn.h> header file. */
			#cmakedefine HAVE_DLFCN_H 1

			/* Define to 1 if you have the <fcntl.h> header file. */
			#cmakedefine HAVE_FCNTL_H 1

			/* Define to 1 if you have the `floor' function. */
			#cmakedefine HAVE_FLOOR 1

			/* Define to 1 if you have the `getopt' function. */
			#cmakedefine HAVE_GETOPT 1

			/* Define as 0 or 1 according to the floating point format suported by the
			   machine */
			#cmakedefine HAVE_IEEEFP 1

			/* Define to 1 if the system has the type `int16'. */
			#cmakedefine HAVE_INT16

			/* Define to 1 if the system has the type `int32'. */
			#cmakedefine HAVE_INT32

			/* Define to 1 if the system has the type `int8'. */
			#cmakedefine HAVE_INT8

			/* Define to 1 if you have the <inttypes.h> header file. */
			#cmakedefine HAVE_INTTYPES_H 1

			/* Define to 1 if you have the `isascii' function. */
			#cmakedefine HAVE_ISASCII 1

			/* Define to 1 if you have the `lfind' function. */
			#cmakedefine HAVE_LFIND 1

			/* Define to 1 if you have the `c' library (-lc). */
			#cmakedefine HAVE_LIBC 1

			/* Define to 1 if you have the `m' library (-lm). */
			#cmakedefine HAVE_LIBM 1

			/* Define to 1 if you have the <limits.h> header file. */
			#cmakedefine HAVE_LIMITS_H 1

			/* Define to 1 if you have the <malloc.h> header file. */
			#cmakedefine HAVE_MALLOC_H 1

			/* Define to 1 if you have the `memmove' function. */
			#cmakedefine HAVE_MEMMOVE 1

			/* Define to 1 if you have the <memory.h> header file. */
			#cmakedefine HAVE_MEMORY_H 1

			/* Define to 1 if you have the `memset' function. */
			#cmakedefine HAVE_MEMSET 1

			/* Define to 1 if you have the `mmap' function. */
			#cmakedefine HAVE_MMAP 1

			/* Define to 1 if you have the `pow' function. */
			#cmakedefine HAVE_POW 1

			/* Define if you have POSIX threads libraries and header files. */
			#cmakedefine HAVE_PTHREAD 1

			/* Define to 1 if you have the <search.h> header file. */
			#cmakedefine HAVE_SEARCH_H 1

			/* Define to 1 if you have the `sqrt' function. */
			#cmakedefine HAVE_SQRT 1

			/* Define to 1 if you have the <stdint.h> header file. */
			#cmakedefine HAVE_STDINT_H 1

			/* Define to 1 if you have the <stdlib.h> header file. */
			#cmakedefine HAVE_STDLIB_H 1

			/* Define to 1 if you have the `strcasecmp' function. */
			#cmakedefine HAVE_STRCASECMP 1

			/* Define to 1 if you have the `strchr' function. */
			#cmakedefine HAVE_STRCHR 1

			/* Define to 1 if you have the <strings.h> header file. */
			#cmakedefine HAVE_STRINGS_H 1

			/* Define to 1 if you have the <string.h> header file. */
			#cmakedefine HAVE_STRING_H 1

			/* Define to 1 if you have the `strrchr' function. */
			#cmakedefine HAVE_STRRCHR 1

			/* Define to 1 if you have the `strstr' function. */
			#cmakedefine HAVE_STRSTR 1

			/* Define to 1 if you have the `strtol' function. */
			#cmakedefine HAVE_STRTOL 1

			/* Define to 1 if you have the `strtoul' function. */
			#cmakedefine HAVE_STRTOUL 1

			/* Define to 1 if you have the <sys/stat.h> header file. */
			#cmakedefine HAVE_SYS_STAT_H 1

			/* Define to 1 if you have the <sys/time.h> header file. */
			#cmakedefine HAVE_SYS_TIME_H 1

			/* Define to 1 if you have the <sys/types.h> header file. */
			#cmakedefine HAVE_SYS_TYPES_H 1

			/* Define to 1 if you have the <unistd.h> header file. */
			#cmakedefine HAVE_UNISTD_H 1

			/* Define to 1 if you have the <windows.h> header file. */
			#cmakedefine HAVE_WINDOWS_H 1

			/* Native cpu byte order: 1 if big-endian (Motorola) or 0 if little-endian
			   (Intel) */
			#define HOST_BIGENDIAN ${HOST_BIGENDIAN}

			/* Set the native cpu bit order (FILLORDER_LSB2MSB or FILLORDER_MSB2LSB) */
			#define HOST_FILLORDER ${HOST_FILLORDER}

			/* Support JPEG compression (requires IJG JPEG library) */
			#cmakedefine JPEG_SUPPORT 1

			/* Support LogLuv high dynamic range encoding */
			#cmakedefine LOGLUV_SUPPORT 1

			/* Define to the sub-directory in which libtool stores uninstalled libraries.
			   */
			#cmakedefine LT_OBJDIR 1

			/* Support LZW algorithm */
			#cmakedefine LZW_SUPPORT 1

			/* Support Microsoft Document Imaging format */
			#cmakedefine MDI_SUPPORT 1

			/* Support NeXT 2-bit RLE algorithm */
			#cmakedefine NEXT_SUPPORT 1

			/* Define to 1 if your C compiler doesn't accept -c and -o together. */
			#cmakedefine NO_MINUS_C_MINUS_O  1

			/* Support Old JPEG compresson (read contrib/ojpeg/README first! Compilation
			   fails with unpatched IJG JPEG library) */
			#cmakedefine OJPEG_SUPPORT 1

			/* Name of package */
			#define PACKAGE "${PACKAGE}"

			/* Define to the address where bug reports for this package should be sent. */
			#define PACKAGE_BUGREPORT "${PACKAGE_BUGREPORT}"

			/* Define to the full name of this package. */
			#define PACKAGE_NAME "${PACKAGE_NAME}"

			/* Define to the full name and version of this package. */
			#define PACKAGE_STRING "${PACKAGE_STRING}"

			/* Define to the one symbol short name of this package. */
			#define PACKAGE_TARNAME "${PACKAGE_TARNAME}"

			/* Define to the version of this package. */
			#define PACKAGE_VERSION "${PACKAGE_VERSION}"

			/* Support Macintosh PackBits algorithm */
			#cmakedefine PACKBITS_SUPPORT 1

			/* Support Pixar log-format algorithm (requires Zlib) */
			#cmakedefine PIXARLOG_SUPPORT 1

			/* Define to necessary symbol if this constant uses a non-standard name on
			   your system. */
			#cmakedefine PTHREAD_CREATE_JOINABLE 1

			/* The size of a `int', as computed by sizeof. */
			#define SIZEOF_INT ${SIZEOF_INT}

			/* The size of a `long', as computed by sizeof. */
			#define SIZEOF_LONG ${SIZEOF_LONG}

			/* Define to 1 if you have the ANSI C header files. */
			#cmakedefine STDC_HEADERS 1

			/* Support strip chopping (whether or not to convert single-strip uncompressed
			   images to mutiple strips of specified size to reduce memory usage) */
			#define STRIPCHOP_DEFAULT ${STRIPCHOP_DEFAULT}

			/* Default size of the strip in bytes (when strip chopping enabled) */
			#define STRIP_SIZE_DEFAULT ${STRIP_SIZE_DEFAULT}

			/* Enable SubIFD tag (330) support */
			#cmakedefine SUBIFD_SUPPORT

			/* Support ThunderScan 4-bit RLE algorithm */
			#cmakedefine THUNDER_SUPPORT

			/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
			#cmakedefine TIME_WITH_SYS_TIME 1

			/* Define to 1 if your <sys/time.h> declares `struct tm'. */
			#cmakedefine TM_IN_SYS_TIME 1

			/* Version number of package */
			#define VERSION "${VERSION}"

			/* Define to 1 if your processor stores words with the most significant byte
			   first (like Motorola and SPARC, unlike Intel and VAX). */
			#cmakedefine WORDS_BIGENDIAN

			/* Define to 1 if the X Window System is missing or not being used. */
			#cmakedefine X_DISPLAY_MISSING 1

			/* Support Deflate compression */
			#cmakedefine ZIP_SUPPORT 1

			/* Number of bits in a file offset, on hosts where this is settable. */
			#cmakedefine _FILE_OFFSET_BITS 1

			/* Define for large files, on AIX-style hosts. */
			#cmakedefine _LARGE_FILES 1

			/* Define to empty if `const' does not conform to ANSI C. */
			#cmakedefine const

			/* Define to `__inline__' or `__inline' if that's what the C compiler
			   calls it, or to nothing if 'inline' is not supported under any name.  */
			#ifndef __cplusplus
			#cmakedefine inline
			#endif

			/* Define to `long' if <sys/types.h> does not define. */
			#cmakedefine off_t

			/* Define to `unsigned' if <sys/types.h> does not define. */
			#cmakedefine size_t

		